# Generated by Django 5.1.4 on 2026-09-10 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='spin_discount_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='spin_discount_pct',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
