# Generated by Django 5.1.4 on 2026-09-11 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadspaceBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow', models.CharField(default='New Collection · 2026', max_length=100)),
                ('title', models.CharField(default='Vanki Rings', max_length=255)),
                ('desc_line1', models.CharField(default='Traditional South Indian finger rings, handcrafted in 925 sterling silver.', max_length=255)),
                ('desc_line2', models.CharField(blank=True, default='Worn with mehndi or bridal wear — a timeless symbol of grace.', max_length=255)),
                ('offer_pct', models.CharField(blank=True, default='20% OFF', max_length=50)),
                ('offer_label', models.CharField(blank=True, default='on all Vanki Rings · Limited Time', max_length=150)),
                ('button_text', models.CharField(default='Shop Now', max_length=50)),
                ('button_link', models.CharField(default='/products', max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='leadspace/')),
                ('image_url', models.CharField(blank=True, help_text='External/asset image URL or fallback', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Leadspace Banner',
                'verbose_name_plural': 'Leadspace Banners',
                'db_table': 'leadspace_banners',
                'ordering': ['-is_active', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Notification announcement text')),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Notification Bar',
                'verbose_name_plural': 'Notification Bars',
                'db_table': 'notification_bars',
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StorySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow', models.CharField(default='Our Story', max_length=100)),
                ('title', models.CharField(default='Crafted with Passion, Worn with Pride', max_length=255)),
                ('paragraph_1', models.TextField(default='Founded in 2024, Kasavelli was born from a love for traditional Indian jewellery-making. Every piece is handcrafted by skilled artisans using 925 hallmarked sterling silver — hypoallergenic, durable, and timeless.')),
                ('paragraph_2', models.TextField(blank=True, default='We blend centuries-old craftsmanship with modern design sensibilities to create jewellery that tells a story. From bridal sets to everyday wear, each Kasavelli piece is a work of art.')),
                ('badge_number', models.CharField(default='925', max_length=50)),
                ('badge_label', models.CharField(default='Hallmarked Silver', max_length=100)),
                ('stat1_value', models.CharField(default='100+', max_length=50)),
                ('stat1_label', models.CharField(default='Unique Designs', max_length=100)),
                ('stat2_value', models.CharField(default='500+', max_length=50)),
                ('stat2_label', models.CharField(default='Happy Customers', max_length=100)),
                ('stat3_value', models.CharField(default='925', max_length=50)),
                ('stat3_label', models.CharField(default='Silver Purity', max_length=100)),
                ('button_text', models.CharField(default='View Collection', max_length=50)),
                ('button_link', models.CharField(default='/products', max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='story/')),
                ('image_url', models.CharField(blank=True, help_text='External/asset image URL or fallback', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Story Section',
                'verbose_name_plural': 'Story Sections',
                'db_table': 'story_sections',
                'ordering': ['-is_active', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WhyChooseCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('icon_type', models.CharField(choices=[('shield', 'Shield / Certified'), ('heart', 'Heart / Handpicked'), ('truck', 'Truck / Delivery'), ('returns', 'Trending / 30-Day Returns'), ('gift', 'Gift / Packaging'), ('sparkles', 'Sparkles / Made in India'), ('custom', 'Custom Icon')], default='shield', max_length=50)),
                ('custom_icon_svg', models.TextField(blank=True, help_text='Optional custom SVG path or raw SVG')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Why Choose Card',
                'verbose_name_plural': 'Why Choose Cards',
                'db_table': 'why_choose_cards',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.AlterModelOptions(
            name='banner',
            options={'ordering': ['display_order', '-created_at'], 'verbose_name': 'Banner', 'verbose_name_plural': 'Banners'},
        ),
    ]
