# Generated by Django 5.1.4 on 2026-09-12 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_leadspacebanner_notificationbar_storysection_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpinWheelSlice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='e.g. 10% OFF, Better Luck!', max_length=100)),
                ('percentage', models.PositiveIntegerField(default=0, help_text='Discount percentage (0 for Better Luck / no discount)')),
                ('color', models.CharField(default='#551756', help_text='Slice background color hex code', max_length=50)),
                ('text_color', models.CharField(default='#e8c547', help_text='Slice text color hex code', max_length=50)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Spin Wheel Slice',
                'verbose_name_plural': 'Spin Wheel Slices',
                'db_table': 'spin_wheel_slices',
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
