# Generated by Django 5.1.4 on 2026-09-12 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_spinwheelslice'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadspacebanner',
            name='trust_tag1',
            field=models.CharField(blank=True, default='925 Certified', max_length=80),
        ),
        migrations.AddField(
            model_name='leadspacebanner',
            name='trust_tag2',
            field=models.CharField(blank=True, default='Free Shipping', max_length=80),
        ),
        migrations.AddField(
            model_name='leadspacebanner',
            name='trust_tag3',
            field=models.CharField(blank=True, default='Easy Returns', max_length=80),
        ),
    ]
