# Generated by Django 5.1.4 on 2026-09-13 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_add_trust_tags_to_leadspace_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationbar',
            name='icon_type',
            field=models.CharField(choices=[('truck', '🚚 Truck / Delivery'), ('speaker', '📢 Speaker / Announcement'), ('tag', '🏷️ Tag / Offer'), ('shield', '🛡️ Shield / Certified'), ('gift', '🎁 Gift / Packaging'), ('star', '⭐ Star / Featured'), ('heart', '❤️ Heart / Handpicked'), ('sparkles', '✨ Sparkles / Made in India'), ('returns', '🔄 Returns / Exchange'), ('none', '— No Icon')], default='truck', help_text='Icon shown before the notification text', max_length=20),
        ),
    ]
